name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Build & Push
      run: |       
        docker image build -t spbravo/gitops:qrcode1.0 .
        docker push ghcr.io/spbravo/gitops:qrcode1.0
