name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |    
        docker login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} https://grc.io
        docker image build -t grc.io/spbravo/gitops:qrcode1.9 .
        docker push grc.io/spbravo/gitops:qrcode1.9
