name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build & Push
      run: |    
        docker image build -t ghcr.io/spbravo/gitops:qrcode1.9 .
        docker push ghcr.io/spbravo/gitops:qrcode1.9
